=encoding utf-8

=head1 おなまえ

Moxy::Manual::InstallJA - Moxy インストールマニュアル(ニホンゴバン)

=head1 実際にインストールしてみるみる

まずは Moxy 本体をダウンロードします。Moxy 本体は現在のところ svn でのみ配布されています。

基本的にはごく標準的な Perl スクリプトの配布方法をとっていますので

    svn co http://code.mfac.jp/svn/Moxy/
    cd Moxy
    perl Makefile.PL
    make test
    ./moxy.pl -c config.yaml

という手順ですぐに使いはじめることができます。

