=encoding utf-8

=for stopwords localsrc HTML

=head1 おなまえ

Moxy::Manual::PluginGuideJA - Moxy Plugin利用ガイド(ニホンゴバン)

=head1 はじめに

Moxy には様々なプラグインが同梱されています。殆どの場合に便利なものから、特定条件下でのみ

役に立つものまで様々です。ここでは、各プラグインの解説をざっくりと行ないます。

=head1 ControlPanel

画面上部に UserAgent 選択などの設定画面を表示します。現状ではこれ以外で UA の切替が出来ないため、
必須で設定する必要があるプラグインです。
QRCode, UserID, ShowHTTPHeaders プラグインの実行にも必要です。

=head1 CookieCutter

クライアント(ブラウザ)からのCookieの送信をカットします。DoCoMo 端末の挙動をエミュレートしています。

=head1 DisableTableTag

HTML 中で使用されているTABLE関連のタグを無効化します。<td>や<th>の中に書いたテキストがそのまま
（表組みされずに）表示されます。UAを DoCoMo 端末にしている場合のみ動作します。

=head1 FlashUseImgTag

<img src="xxxx.swf" /> のように、imgタグでflashファイルを指定している場合に、 object タグに変換して
ブラウザ上で閲覧できるようにします。UA を au 端末にしている場合のみ動作します。

=head1 GPS

位置情報を利用しているサイトを閲覧する際に、位置情報の送信をエミュレートします。
DoCoMo の i エリアと、au 、WILLCOM の位置情報送信機能に対応しています。

=head1 HTMLWidth

選択している UA の画面の幅に合わせて表示する HTML の幅を調整します。

=head1 HTTPEnv

選択している UA の仕様にあわせて、各種情報(au のMAX_PDUなど)をHTTP Header で送信します。

=head1 Pictogram

選択している UA にあわせて絵文字を表示します。各種絵文字の記述方法（実体参照、au におけるimg localsrc など)
に対応しています。利用する場合、makeを使ってインストールを行い、絵文字のscrapingを実行するか、scrape.plを
別途実行する必要があります。

=head1 QRCode

現在参照しているページのURLをQRCodeで表示します。最終的に実機で確認する場合に便利です。

=head1 RefererCutter

Referer の送信をカットします。DoCoMo 端末の挙動をエミュレートしています。

=head1 ShowHTTPHeaders

Request と Response の HTTP Header を ControlPanel に表示します。

=head1 UserAgentSwitcher

UA を切り替えられるようになります。Moxyの最も基本的なPluginです。

=head1 UserID

au 端末のサブスクライバIDの送信をエミュレートします。

=head1 XMLisHTML

DoCoMo 用のサイトで XHTML で記述されていて、Content-Typeがapplication/xhtml+xmlになっている場合、ブラウザ
側で携帯サイト特有の記述がXMLとして不正な形式と判断されて、画面表示されない場合があります。
このプラグインを設定すると、上記ケースでContent-Typeをtext/htmlに差し替えて現象を回避します。

